platform :ios, '16.0'
use_frameworks!

target 'TestApp' do
 pod 'SAPCommon', :podspec => "../SAPCommon/10.0.0/SAPCommon.podspec"
 pod 'SAPFoundation', :podspec => "../SAPFoundation/10.0.0/SAPFoundation.podspec"
 pod 'SAPFiori', :podspec => "../SAPFiori/10.0.0/SAPFiori.podspec"
 pod 'SAPFioriFlows', :podspec => "../SAPFioriFlows/10.0.0/SAPFioriFlows.podspec"
 pod 'SAPOData', :podspec => "../SAPOData/10.0.0/SAPOData.podspec"
 pod 'SAPOfflineOData', :podspec => "../SAPOfflineOData/10.0.0/SAPOfflineOData.podspec"
 pod 'SAPML', :podspec => "../SAPML/10.0.0/SAPML.podspec"
end
